### ISSUE TITLE
window.Filters is undefined

### ISSUE THREAD

**Issue by Smok455** [TowhidKashem/snapchat-clone#4]
Hi,
I getting this error:
TypeError: Cannot read property 'deform' of undefined

**Comment by TowhidKashem** [comment]
Sounds like you failed to install the filter library, that should have been done automatically for you after running `npm install` due to the post install hook. Anyway you can check if this file exists `filters/build/filters.min.js`. If it doesn't try running `npm run install-filter-deps` and if that doesn't work just try running just `npm run gulp` all from your terminal.
